name: Java CI
on: push
jobs:
  Clone-Down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    needs: Clone-Down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - run: chmod +x ci/build-app.sh
  Test:
    needs: Clone-Down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name : Test
        run: ci/unit-test-app.sh
      